import { z } from 'zod'

import { demoSubmissionSchema } from './demo-request.ts'

/**
 * One outbound port, not two — operator-confirmed, and the blueprint is explicit
 * about why.
 *
 * The `/demo` Server Action calls `capture(lead)` and nothing else. The
 * server-side conversion dispatch (Q21) happens **inside** the implementation
 * and is explicitly non-fatal.
 *
 * Two reasons this is one port rather than two. It keeps the action's test
 * surface to a single fake. And the two operations have different failure
 * semantics — a failed capture loses a customer, a failed conversion event
 * loses only an optimisation signal — so the asymmetry is enforced where a
 * caller cannot accidentally make a lead depend on an ad platform being
 * reachable.
 *
 * Which boundary owns a sales lead is **Q22, open**. A `/demo` submission is a
 * prospective *customer organization*: it has no listing, no `organization_id`
 * (it is not an organization yet) and no place in the marketplace pipeline, so
 * `listing.leads` is the wrong home however column-compatible it looks. The
 * only implementation that ships appends to a file. **DEBT-08.**
 */

export const capturedLeadSchema = demoSubmissionSchema.extend({
  /** UUIDv7 in the real implementation; generated by the caller (D-07). */
  id: z.string().min(1),
  receivedAt: z.iso.datetime(),
})

export type CapturedLead = z.infer<typeof capturedLeadSchema>

export interface LeadSink {
  capture(lead: CapturedLead): Promise<void>
}
